HairSalon/Models/Client.cs
namespace HairSalon.Models
{
  public class Client
  {
    public int ClientId { get; set; }
    public string Name { get; set; }
    public int StylistId { get; set; }
    public virtual Stylist Stylist { get; set; }
  }
}

HairSalon/Models/SalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models
{
  public class HairSalonContext : DbContext
  {
    public DbSet<Stylist> Stylists { get; set; } //update this
    public DbSet<Client> Clients { get; set; } //update this

    public HairSalonContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

HairSalon/Models/Stylist.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
  public class Stylist
  {
    public int StylistId { get; set; }
    public string Name { get; set; }
    public string Specialty { get; set; }

    public Stylist()
    {
      this.Clients = new HashSet<Client>();
    }

    public virtual ICollection<Client> Clients { get; set; }
  }
}

HairSalon/Controllers/ClientsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using System;

namespace HairSalon.Controllers
{
  public class ClientsController : Controller
  {
    private readonly HairSalonContext _db;

    public ClientsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Create(int id)
    {
      ViewBag.StylistId = id;
      return View();
    }

    [HttpPost]
    public ActionResult Create(Client client)
    {
      _db.Clients.Add(client);
      _db.SaveChanges();
      return RedirectToAction("Details", "Stylists", new { id = client.StylistId });
    }
  }
}

HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace HairSalon.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index() { 
      return View(); 
    }
  }
}

HairSalon/Controllers/StylistsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;

namespace HairSalon.Controllers
{
  public class StylistsController : Controller
  {
    private readonly HairSalonContext _db;

    public StylistsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Stylist> model = _db.Stylists.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Stylist stylist)
    {
      _db.Stylists.Add(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      List<Client> clientsForThisStylist = _db.Clients.ToList().Where(client => client.StylistId == id).ToList();
      ViewBag.ClientsList = clientsForThisStylist;
      Stylist selectedStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(selectedStylist);
    }
  }
}

HairSalon/Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h4>Add a client</h4>

@using (Html.BeginForm())
{
  <input hidden value="@ViewBag.StylistId" name="StylistId" id="StylistId">

  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name, null, new {@class="form-control"})

  <input type="submit" value="Add client" class="mt-3 btn btn-primary" />
}
<p>@Html.ActionLink("Back to stylist page", "Details", "Stylists", new { id = @ViewBag.StylistId }, new {@class="mt-3 btn btn-warning"} )</p>

HairSalon/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}
  
<h1>Salon Management</h1>

<h3>@Html.ActionLink("View stylists", "Index", "Stylists", null, new {@class="mt-3 btn btn-primary"})</h3>

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    <div class="container p-3">
      @RenderBody()
    </div>
  </body>
</html>

HairSalon/Views/Stylists/Create.cshtml
@{
  Layout = "_Layout";
}

<h2>Add a stylist</h2>

@model HairSalon.Models.Stylist

@using(@Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name, null, new {@class="form-control"})
  @Html.LabelFor(model => model.Specialty)
  @Html.TextBoxFor(model => model.Specialty, null, new {@class="form-control"})
  <input type="submit" value="Add stylist" class="mt-3 btn btn-primary"/>
}

@Html.ActionLink("Back to stylist list", "Index", null, null, new {@class="mt-3 btn btn-warning"})

HairSalon/Views/Stylists/Details.cshtml
@using HairSalon.Models
@using System
@{
  Layout = "_Layout";
}
@model HairSalon.Models.Stylist

<h2>Stylist Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>
<h3>@Html.DisplayNameFor(model => model.Specialty): @Html.DisplayFor(model => model.Specialty)<h3>

@if(@ViewBag.ClientsList.Count == 0)
{
  <p>There are no clients for this stylist yet.</p>
}
else
{
  <h3>Clients: </h3>
  <ul class="list-group">
    @foreach(Client client in @ViewBag.ClientsList)
    {
      <li class="list-group-item text-sm">@client.Name</li>
    }
  </ul>
}

<p>@Html.ActionLink("Add a new client", "Create", "Clients", new { id = @Model.StylistId}, new {@class="mt-3 btn btn-primary"})</p>
<p>@Html.ActionLink("View all stylists", "Index", null, null, new {@class="btn btn-warning"})</p>

HairSalon/Views/Stylists/Index.cshtml
@using HairSalon.Models

@{
  Layout = "_Layout";
}

<h2>All stylists</h2>

@if(Model.Count == 0)
{
  <h3>There are no stylists</h3>
}

<ul class="list-group">
  @foreach (Stylist stylist in Model)
  {
    <li class="list-group-item">@Html.ActionLink($"{@stylist.Name}", "Details", new { id = stylist.StylistId }) </li>
  }
</ul>

<p>@Html.ActionLink("Add a stylist", "Create", null, null, new {@class="mt-3 btn btn-primary"})</p>
<p>@Html.ActionLink("Go home", "Index", "Home", null, new {@class="btn btn-warning"})</p>